"""Drawing primitives and font surgery for the TfcIcons glyph font.

TfcIcons.ttf was originally generated by Fontello and checked in without its
SVG sources, so the only way to add a glyph used to be to re-upload the whole
set to a web service and hope the existing code points came back unchanged.
This module replaces that with a reproducible, reviewable build: glyphs are
drawn here in Python, merged into the existing font in place, and the code
points already in the font are never touched.

Coordinate system
-----------------
Glyphs are drawn in *design space*: a 1000x1000 square with the origin at its
top-left corner and **y pointing down**, the way every drawing program and SVG
works. :func:`_to_font` flips it onto the font's em box (y up, baseline 0,
ascender 850) at the very end, so nothing below has to think about it.

Material's icons put ~2/24 of the box between the artwork and the edge and
draw their strokes ~2/24 thick; :data:`MARGIN` and :data:`STROKE` are those
ratios in design units, which is what keeps these glyphs from looking heavier
or lighter than the Material icons they sit beside in the picker.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import pathops
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont

# --- The design grid -------------------------------------------------------

EM = 1000
ASCENT = 850
DESCENT = -150

#: Keep the artwork inside this much of the 1000-unit square.
MARGIN = 60
#: Default stroke weight. 72/1000 is Material's 1.73/24 hairline-plus.
STROKE = 72
#: A lighter weight for interior detail that would otherwise clog up at 24px.
THIN = 52

LEFT = MARGIN
RIGHT = EM - MARGIN
TOP = MARGIN
BOTTOM = EM - MARGIN
CX = EM / 2
CY = EM / 2

BUTT = pathops.LineCap.BUTT_CAP
ROUND = pathops.LineCap.ROUND_CAP
SQUARE = pathops.LineCap.SQUARE_CAP
MITER = pathops.LineJoin.MITER_JOIN
ROUND_JOIN = pathops.LineJoin.ROUND_JOIN


def _to_font(path: pathops.Path) -> pathops.Path:
    """Flip design space (y down, 0..1000) onto the em box (y up, -150..850)."""
    return path.transform(1, 0, 0, -1, 0, ASCENT)


def merge(*paths: pathops.Path) -> pathops.Path:
    """Union. pathops' own helpers draw into a pen and return None; these two
    hand back a Path so shapes compose as expressions."""
    out = pathops.Path()
    pathops.union(list(paths), out.getPen())
    return out


def subtract(subject: pathops.Path, clip: pathops.Path) -> pathops.Path:
    out = pathops.Path()
    pathops.difference([subject], [clip], out.getPen())
    return out


# --- Shape primitives ------------------------------------------------------
#
# Every primitive returns a closed pathops.Path in design space. Direction is
# irrelevant here: Ink.build() runs a final simplify() that rewrites every
# contour to the direction TrueType's non-zero fill needs.


def rect(x: float, y: float, w: float, h: float, r: float = 0) -> pathops.Path:
    """Axis-aligned rectangle, optionally with corner radius `r`."""
    p = pathops.Path()
    pen = p.getPen()
    if r <= 0:
        pen.moveTo((x, y))
        pen.lineTo((x + w, y))
        pen.lineTo((x + w, y + h))
        pen.lineTo((x, y + h))
        pen.closePath()
        return p
    r = min(r, w / 2, h / 2)
    k = r * (1 - 0.5522847498)  # cubic circle approximation
    pen.moveTo((x + r, y))
    pen.lineTo((x + w - r, y))
    pen.curveTo((x + w - k, y), (x + w, y + k), (x + w, y + r))
    pen.lineTo((x + w, y + h - r))
    pen.curveTo((x + w, y + h - k), (x + w - k, y + h), (x + w - r, y + h))
    pen.lineTo((x + r, y + h))
    pen.curveTo((x + k, y + h), (x, y + h - k), (x, y + h - r))
    pen.lineTo((x, y + r))
    pen.curveTo((x, y + k), (x + k, y), (x + r, y))
    pen.closePath()
    return p


def box(x0: float, y0: float, x1: float, y1: float, r: float = 0) -> pathops.Path:
    """Rectangle given by two corners rather than an origin and a size."""
    return rect(min(x0, x1), min(y0, y1), abs(x1 - x0), abs(y1 - y0), r)


def ellipse(cx: float, cy: float, rx: float, ry: float) -> pathops.Path:
    p = pathops.Path()
    pen = p.getPen()
    kx, ky = rx * 0.5522847498, ry * 0.5522847498
    pen.moveTo((cx, cy - ry))
    pen.curveTo((cx + kx, cy - ry), (cx + rx, cy - ky), (cx + rx, cy))
    pen.curveTo((cx + rx, cy + ky), (cx + kx, cy + ry), (cx, cy + ry))
    pen.curveTo((cx - kx, cy + ry), (cx - rx, cy + ky), (cx - rx, cy))
    pen.curveTo((cx - rx, cy - ky), (cx - kx, cy - ry), (cx, cy - ry))
    pen.closePath()
    return p


def circle(cx: float, cy: float, r: float) -> pathops.Path:
    return ellipse(cx, cy, r, r)


def poly(points: list[tuple[float, float]]) -> pathops.Path:
    p = pathops.Path()
    pen = p.getPen()
    pen.moveTo(points[0])
    for pt in points[1:]:
        pen.lineTo(pt)
    pen.closePath()
    return p


def stroke(
    points: list[tuple[float, float]],
    w: float = STROKE,
    cap=BUTT,
    join=MITER,
    close: bool = False,
    dash: list[float] | None = None,
) -> pathops.Path:
    """An open polyline given body: the outline of `points` stroked `w` wide."""
    p = pathops.Path()
    pen = p.getPen()
    pen.moveTo(points[0])
    for pt in points[1:]:
        pen.lineTo(pt)
    if close:
        pen.closePath()
    else:
        pen.endPath()
    p.stroke(w, cap, join, 4.0, dash)
    # Round caps and joins come out of Skia as conics, which neither the
    # TrueType pen nor pathops' own segment iterator can read.
    p.convertConicsToQuads(0.1)
    return p


def curve(
    segments: list,
    w: float = STROKE,
    cap=BUTT,
    join=ROUND_JOIN,
    close: bool = False,
    dash: list[float] | None = None,
) -> pathops.Path:
    """Stroke a path of mixed line and cubic segments.

    `segments` starts with a point and continues with either a point (line to)
    or a 3-tuple of points (cubic curve through two controls to an end point).
    """
    p = pathops.Path()
    pen = p.getPen()
    pen.moveTo(segments[0])
    for seg in segments[1:]:
        if len(seg) == 3 and not isinstance(seg[0], (int, float)):
            pen.curveTo(*seg)
        else:
            pen.lineTo(seg)
    if close:
        pen.closePath()
    else:
        pen.endPath()
    p.stroke(w, cap, join, 4.0, dash)
    # Round caps and joins come out of Skia as conics, which neither the
    # TrueType pen nor pathops' own segment iterator can read.
    p.convertConicsToQuads(0.1)
    return p


def fill(segments: list) -> pathops.Path:
    """A closed, filled region bounded by line and cubic segments.

    Same segment format as :func:`curve`, but the path is filled rather than
    stroked -- the way to draw a solid shape with curved sides, such as a fan
    blade or a pump vane.
    """
    p = pathops.Path()
    pen = p.getPen()
    pen.moveTo(segments[0])
    for seg in segments[1:]:
        if len(seg) == 3 and not isinstance(seg[0], (int, float)):
            pen.curveTo(*seg)
        else:
            pen.lineTo(seg)
    pen.closePath()
    return p


def hexagon(cx: float, cy: float, w: float, h: float) -> pathops.Path:
    """A flats-left-and-right hexagon -- the shape of every process fitting."""
    hw, hh = w / 2, h / 2
    return poly(
        [
            (cx - hw, cy - hh * 0.5),
            (cx, cy - hh),
            (cx + hw, cy - hh * 0.5),
            (cx + hw, cy + hh * 0.5),
            (cx, cy + hh),
            (cx - hw, cy + hh * 0.5),
        ]
    )


def rotated(shape_fn, cx: float, cy: float, angle: float) -> pathops.Path:
    """Draw `shape_fn(pt)` in a frame rotated `angle` degrees about (cx, cy).

    `pt(x, y)` maps a point given relative to the centre -- x along the frame's
    own axis -- into design space.
    """
    a = math.radians(angle)
    ca, sa = math.cos(a), math.sin(a)

    def pt(x, y):
        return (cx + x * ca - y * sa, cy + x * sa + y * ca)

    return shape_fn(pt)


def ring(cx: float, cy: float, r: float, w: float = STROKE) -> pathops.Path:
    """A circle outline of width `w` centred on radius `r`."""
    return subtract(circle(cx, cy, r + w / 2), circle(cx, cy, r - w / 2))


def outline(
    x0: float, y0: float, x1: float, y1: float, w: float = STROKE, r: float = 0
) -> pathops.Path:
    """A rectangle outline of width `w` centred on the given rectangle."""
    h = w / 2
    outer = box(x0 - h, y0 - h, x1 + h, y1 + h, r + h if r else 0)
    inner = box(x0 + h, y0 + h, x1 - h, y1 - h, max(r - h, 0) if r else 0)
    return subtract(outer, inner)


def arc(
    cx: float,
    cy: float,
    r: float,
    a0: float,
    a1: float,
    w: float = STROKE,
    cap=BUTT,
) -> pathops.Path:
    """A stroked arc. Angles are degrees, measured clockwise from 3 o'clock
    (design space has y pointing down, so positive angles sweep downward)."""
    p = pathops.Path()
    steps = max(2, int(abs(a1 - a0) / 12))
    pts = []
    for i in range(steps + 1):
        a = math.radians(a0 + (a1 - a0) * i / steps)
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    pen = p.getPen()
    pen.moveTo(pts[0])
    for pt in pts[1:]:
        pen.lineTo(pt)
    pen.endPath()
    p.stroke(w, cap, ROUND_JOIN, 4.0, None)
    # Round caps and joins come out of Skia as conics, which neither the
    # TrueType pen nor pathops' own segment iterator can read.
    p.convertConicsToQuads(0.1)
    return p


def sine(
    x0: float, x1: float, cy: float, amp: float, cycles: float = 1.0, w: float = STROKE
) -> pathops.Path:
    """A stroked sine wave — the AC half of the IEC converter symbols."""
    p = pathops.Path()
    pen = p.getPen()
    steps = max(16, int(24 * cycles))
    pts = [
        (
            x0 + (x1 - x0) * i / steps,
            cy - amp * math.sin(2 * math.pi * cycles * i / steps),
        )
        for i in range(steps + 1)
    ]
    pen.moveTo(pts[0])
    for pt in pts[1:]:
        pen.lineTo(pt)
    pen.endPath()
    p.stroke(w, ROUND, ROUND_JOIN, 4.0, None)
    # Round caps and joins come out of Skia as conics, which neither the
    # TrueType pen nor pathops' own segment iterator can read.
    p.convertConicsToQuads(0.1)
    return p


def arrow(
    x0: float,
    y0: float,
    x1: float,
    y1: float,
    w: float = STROKE,
    head: float = 150,
) -> pathops.Path:
    """A line from (x0,y0) to (x1,y1) with a solid triangular head at the end."""
    dx, dy = x1 - x0, y1 - y0
    length = math.hypot(dx, dy) or 1
    ux, uy = dx / length, dy / length
    px, py = -uy, ux
    base_x, base_y = x1 - ux * head, y1 - uy * head
    shaft = stroke([(x0, y0), (base_x + ux * 4, base_y + uy * 4)], w, BUTT)
    tip = poly(
        [
            (x1, y1),
            (base_x + px * head * 0.52, base_y + py * head * 0.52),
            (base_x - px * head * 0.52, base_y - py * head * 0.52),
        ]
    )
    return merge(shaft, tip)


# --- Glyph assembly --------------------------------------------------------


@dataclass
class Ink:
    """Accumulates the marks of one glyph.

    `add` unions a shape onto the glyph, `sub` knocks one out. Both are kept as
    lists and resolved in one pass in :meth:`build`, so a hole punched before
    the shape that fills it still comes out right.
    """

    adds: list[pathops.Path] = field(default_factory=list)
    subs: list[pathops.Path] = field(default_factory=list)
    #: Advance width; defaults to the em square.
    width: int = EM

    def add(self, *shapes: pathops.Path) -> "Ink":
        self.adds.extend(shapes)
        return self

    def sub(self, *shapes: pathops.Path) -> "Ink":
        self.subs.extend(shapes)
        return self

    def build(self) -> pathops.Path:
        merged = merge(*self.adds)
        if self.subs:
            merged = subtract(merged, merge(*self.subs))
        # fix_winding + clockwise=True is what makes TrueType's non-zero fill
        # rule see outer contours as filled and inner ones as holes.
        return pathops.simplify(_to_font(merged), fix_winding=True, clockwise=True)


def to_tt_glyph(path: pathops.Path):
    """Quadratic-ise the outline and hand back a `glyf` entry."""
    pen = TTGlyphPen(glyphSet=None)
    path.draw(Cu2QuPen(pen, max_err=1.0))
    glyph = pen.glyph()
    glyph.recalcBounds(glyfTable=None)
    return glyph


def merge_into_font(font_path: str, glyphs: dict[str, tuple[int, Ink]]) -> None:
    """Add `glyphs` (name -> (code point, Ink)) to the font at `font_path`.

    Glyphs already in the font are left byte-for-byte alone, which is the whole
    point: the eight Fontello code points already stored in saved pages must
    keep resolving to the same artwork.
    """
    font = TTFont(font_path)
    cmap_existing = font.getBestCmap()
    for name, (code, _) in glyphs.items():
        if code in cmap_existing and cmap_existing[code] != name:
            raise SystemExit(
                f"U+{code:04X} is already {cmap_existing[code]!r}; refusing to "
                f"reassign it to {name!r}"
            )

    glyf = font["glyf"]
    hmtx = font["hmtx"]
    order = font.getGlyphOrder()
    for name, (_, ink) in glyphs.items():
        glyf[name] = to_tt_glyph(ink.build())
        hmtx[name] = (ink.width, glyf[name].xMin if glyf[name].numberOfContours else 0)
        if name not in order:
            order = order + [name]
    font.setGlyphOrder(order)
    glyf.glyphOrder = order
    font["maxp"].numGlyphs = len(order)

    for table in font["cmap"].tables:
        # The format 0 (Macintosh Roman) subtable only addresses U+0000..U+00FF
        # and would refuse to compile with a Private Use code point in it.
        if table.format == 0:
            continue
        for name, (code, _) in glyphs.items():
            table.cmap[code] = name

    font["maxp"].recalc(font)
    font["head"].modified = 0  # keep the build reproducible
    font.save(font_path)
