// GENERATED FILE -- do not edit by hand.
//
// Rebuilt by tools/icons/build.sh, which draws these glyphs into
// assets/fonts/TfcIcons.ttf and then writes this binding from the same list,
// so a name and its code point cannot drift apart.
//
// Material and Font Awesome have no motor, no VFD, no proximity sensor and no
// pump; these fill that gap for mimic pages.

import 'package:flutter/widgets.dart';

/// Every industrial glyph, by the name it serialises as, in picker order.
const Map<String, IconData> industrialIcons = <String, IconData>{
  'sensor_proximity': IconData(0xe809,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_photoeye': IconData(0xe80a,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_limit_switch': IconData(0xe80b,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_temperature': IconData(0xe80c,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_pressure': IconData(0xe80d,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_level': IconData(0xe80e,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_flow': IconData(0xe80f,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'sensor_encoder': IconData(0xe810,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'load_cell': IconData(0xe811,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'motor': IconData(0xe812,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'motor_circle': IconData(0xe813,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'gearmotor': IconData(0xe814,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'servo_motor': IconData(0xe815,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'gearbox': IconData(0xe816,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'vfd': IconData(0xe817,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'pump': IconData(0xe818,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'pump_circle': IconData(0xe819,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'valve': IconData(0xe81a,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'valve_solenoid': IconData(0xe81b,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'valve_actuated': IconData(0xe81c,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'fan': IconData(0xe81d,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'compressor': IconData(0xe81e,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'tank': IconData(0xe81f,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'io_module': IconData(0xe820,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'io_digital': IconData(0xe821,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'io_analog': IconData(0xe822,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'plc': IconData(0xe823,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'hmi_panel': IconData(0xe824,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'cabinet': IconData(0xe825,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'power_supply': IconData(0xe826,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'circuit_breaker': IconData(0xe827,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'e_stop': IconData(0xe828,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'light_curtain': IconData(0xe829,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'terminal_block': IconData(0xe82a,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
  'cylinder_pneumatic': IconData(0xe82b,
      fontFamily: 'TfcIcons', fontPackage: 'tfc'),
};

/// The picker's section headings, and which glyphs sit under each.
const Map<String, List<String>> industrialIconGroups = <String, List<String>>{
  'Sensors': <String>[
    'sensor_proximity',
    'sensor_photoeye',
    'sensor_limit_switch',
    'sensor_temperature',
    'sensor_pressure',
    'sensor_level',
    'sensor_flow',
    'sensor_encoder',
    'load_cell',
  ],
  'Motors & drives': <String>[
    'motor',
    'motor_circle',
    'gearmotor',
    'servo_motor',
    'gearbox',
    'vfd',
  ],
  'Pumps & fluid handling': <String>[
    'pump',
    'pump_circle',
    'valve',
    'valve_solenoid',
    'valve_actuated',
    'fan',
    'compressor',
    'tank',
  ],
  'I/O & control': <String>[
    'io_module',
    'io_digital',
    'io_analog',
    'plc',
    'hmi_panel',
    'cabinet',
    'power_supply',
    'circuit_breaker',
    'e_stop',
    'light_curtain',
    'terminal_block',
    'cylinder_pneumatic',
  ],
};

/// Reverse of [industrialIcons], for serialising an [IconData] back to a name.
final Map<IconData, String> industrialIconNames = <IconData, String>{
  for (final entry in industrialIcons.entries) entry.value: entry.key,
};
